#!/bin/bash
#
# Use in year directory like:
#   ../dev d01.c
#

gcc -g3 -Wall -Wextra -Wconversion -Wdouble-promotion \
  -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion \
  -fsanitize=address,undefined -fsanitize-undefined-trap-on-error \
  -pthread \
  -lcrypto \
  -DNUM_THREADS=$(getconf _NPROCESSORS_ONLN) \
  -std=c2x -pedantic $@ \
  && \
  ./a.out 

