#!/bin/bash

rm -rf bin *.out

set -euo pipefail

mkdir -p bin
files=$(find . -name "*.c" | sort)

set +u
if [ ! -z "$1" ]; then
unset files
files=$1
fi
set -u

for file in $files; do
  gcc -O3 \
    -pthread \
    -lcrypto \
    -DNUM_THREADS=$(getconf _NPROCESSORS_ONLN) \
    -std=c2x -pedantic $file -o bin/$file.out
done

#hyperfine --warmup=1000 --min-runs=500 --shell=none --export-csv=bench.csv $(ls -A1 bin/*)
hyperfine --warmup=10 --min-runs=50 --shell=none --export-csv=bench.csv $(ls -A1 bin/*)

echo
total=$(awk -F"," 'NR > 1 { sum+=$2; std+=$3 } END { print sum" ± "std }' < bench.csv)
echo "Total: $total seconds"


