#!/bin/bash

set -euo pipefail

mkdir -p bin
files=$(find . -name "*.c" | sort)

for file in $files; do
  gcc -O3 -Wall -Wextra -Wconversion -Wdouble-promotion \
    -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion \
    -fsanitize=address,undefined -fsanitize-undefined-trap-on-error \
    -std=c2x -pedantic $file -o bin/$file.out
done

hyperfine --warmup=1000 --min-runs=500 --shell=none --export-csv=bench.csv $(ls -A1 bin/*)

echo
total=$(awk -F"," 'NR > 1 { sum+=$2; std+=$3 } END { print sum" ± "std }' < bench.csv)
echo "Total: $total seconds"

rm -rf bin *.out

